# Generated by Django 5.0.14 on 2026-07-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('scryfall_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('mana_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('cmc', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('type_line', models.CharField(blank=True, max_length=255, null=True)),
                ('oracle_text', models.TextField(blank=True, null=True)),
                ('rarity', models.CharField(blank=True, max_length=20, null=True)),
                ('image_url_normal', models.CharField(blank=True, max_length=512, null=True)),
                ('local_image_path', models.CharField(blank=True, max_length=512, null=True)),
                ('set_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('lang', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_number', models.CharField(max_length=20, unique=True)),
                ('rule_text', models.TextField()),
                ('chapter_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'rules',
                'ordering': ['rule_number'],
                'managed': False,
            },
        ),
    ]
