# Generated by Django 5.0.14 on 2026-07-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('set_type', models.CharField(blank=True, default='', max_length=50)),
                ('released_at', models.CharField(blank=True, default='', max_length=10)),
                ('icon_svg_uri', models.CharField(blank=True, default='', max_length=512)),
                ('card_count', models.IntegerField(default=0)),
                ('parent_code', models.CharField(blank=True, default='', max_length=10)),
                ('digital', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mtg_sets',
                'ordering': ['-released_at'],
            },
        ),
    ]
