# Generated by Django 5.0.14 on 2026-07-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_api', '0002_cardset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManaSymbol',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('svg_uri', models.CharField(max_length=512)),
                ('english', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'mtg_symbols',
            },
        ),
    ]
