# Generated by Django 5.0.14 on 2026-07-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_api', '0003_manasymbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('scryfall_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('mtgjson_uuid', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usd_foil', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eur_foil', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_date', models.CharField(blank=True, default='', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mtg_prices',
            },
        ),
    ]
