# Generated by Django 5.0.14 on 2026-07-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_api', '0004_cardprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('seed_prices', 'Preços das cartas'), ('seed_cards', 'Cartas de coleções recentes'), ('seed_sets', 'Catálogo de coleções'), ('seed_symbols', 'Símbolos de mana')], max_length=40, unique=True)),
                ('enabled', models.BooleanField(default=True, verbose_name='ativa')),
                ('interval_hours', models.PositiveIntegerField(default=24, verbose_name='intervalo (horas)')),
                ('options', models.CharField(blank=True, default='', help_text='Argumentos do comando, ex: --recent 5', max_length=255, verbose_name='argumentos')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='última execução')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='próxima execução')),
                ('status', models.CharField(choices=[('idle', 'Aguardando'), ('running', 'Executando'), ('ok', 'Concluída'), ('error', 'Falhou')], default='idle', max_length=10)),
                ('last_message', models.TextField(blank=True, default='', verbose_name='resultado')),
                ('force_now', models.BooleanField(default=False, help_text='Marque para rodar na próxima verificação do agendador.', verbose_name='executar agora')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tarefa agendada',
                'verbose_name_plural': 'tarefas agendadas',
                'db_table': 'mtg_scheduled_tasks',
                'ordering': ['key'],
            },
        ),
    ]
